### ISSUE TITLE
[ B U G S - v0.2.0]

### ISSUE THREAD

**Issue by Caballlero** [geobra/harbour-shmoose#10]
- when i add a contact i can not see in contact list > NOT Show names of JID's 
- i have problem to delete a contact on aqua fish. 
- Show subscription and availability status > I DON'T SEE THIS FEATURES TOO.     
ALL TESTED ON JOLLA C - AQUA FISH 
# >> THKS FOR SHMOOSE!!!<<

**Comment by geobra** [comment]
Hi

first one:
Didn't you see the added contact in the Contact List at all? Or is just the name missing?

second one:
What's exactly the Problem? Can you select 'delete' from the context menu? What did happen

third one:
I updated the screen shot of the new Contacts page on openrepos. Please check if the page in your installation looks similiar. If not, tell me the differences.

**Comment by Caballlero** [comment]
# Hello  geobra
first one: Neither contact or name
second one: Yes i select 'delete' from the context menu but no delete on AQUA FISH ONLY. 
third one:
![captura_20170216_001](https://cloud.githubusercontent.com/assets/24536606/23046322/de9f5664-f476-11e6-8abc-9559d79450bc.png)

**Comment by Caballlero** [comment]
last activity notification » no work too  : |

**Comment by geobra** [comment]
Okay, I think we discuss different issuses. The v0.2.0 update was all about the contacts page. Please verify that your contacts page looks similar to this one:
https://openrepos.net/sites/default/files/packages/6941/screenshot-shmoose-contacts.png
There are two new icons, which display the subscription and availability status of your contacts.

The main page of your screen shot look okay. I have disabled the Preferences page for now, because currently there is nothing useful to show on it.

You are right, the 'last activity' didn't works for my also. Will have a look at it and fix it in one of the next updates.

Just to be sure: Delete of contacts only didn't work on aqua fish? On Jolla one and Jolla C, its working fine? I had only a Jolla one here to test with. But in theory there shouldn't be a difference.

Are you willing to do some logging and send the result to me? Do you have the terminal app on your device?

**Comment by Caballlero** [comment]
i can not add contact on jolla 1 too.

**Comment by geobra** [comment]
Hi

Okay, please try this:

-> open terminal app
#> harbour-shmoose

-> you should lot of xml stuff. try to remove a contact. Should look like this:

<iq id="c12aa561-d2ba-44d0-b345-425eaf0279b3" type="set">
 <query xmlns="jabber:iq:roster">
  <item jid="user@somejabber.org" name="" subscription="remove"></item>
 </query>
</iq>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<iq id="c12aa561-d2ba-44d0-b345-425eaf0279b3" type="result" to="your@jabber-account.org/shmoose"></iq>

-> try to add a contact. Should look like:

<iq id="ab1834de-49fe-4f7c-bb37-2c1922f09a04" type="set">
 <query xmlns="jabber:iq:roster">
  <item ask="subscribe" jid="newcontact@somejabberserver.org" name="" subscription="none"></item>
 </query>
</iq>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<iq id="ab1834de-49fe-4f7c-bb37-2c1922f09a04" type="result" to="your@jabber-account.org/shmoose"></iq>

When there are some error stanzes on your side, please report this back here.

A name on the contact add page is optional. Just using the jid should work.

Currently I implement MUC. When this is done I will add some more failure handling to be displayed at the UI and with this start the i18n.

**Comment by Caballlero** [comment]
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<
<r xmlns="urn:xmpp:sm:2"></r>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>
<a xmlns="urn:xmpp:sm:2" h="6"></a>
[D] onDone:33 - new contact: lilianasuas@suchat.org,
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>
<iq id="bbfc7cfe-e88a-47d2-a833-c0e088104f6b" type="set">
<query xmlns="jabber:iq:roster">
<item ask="subscribe" jid="lilianasuas@suchat.org" name="" subscription="n
one"></item>
</query>
</iq>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<
<iq lang="es" to="carlosgonz@suchat.org/10361497547743699916378891" from="ca
rlosgonz@suchat.org" type="error" id="bbfc7cfe-e88a-47d2-a833-c0e088104f6b">
<query xmlns="jabber:iq:roster">
<item ask="subscribe" jid="lilianasuas@suchat.org"></item>
</query>
<error code="400" type="modify">
<bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></bad-request>
<text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="es">Possessing 'as
k' attribute is not allowed by RFC6121</text>
</error>
</iq>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<
<r xmlns="urn:xmpp:sm:2"></r>
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>>
<a xmlns="urn:xmpp:sm:2" h="7"></a>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<<<<
<iq to="carlosgonz@suchat.org/10361497547743699916378891" from="suchat.org"
type="get" id="4412104846438474441">
<ping xmlns="urn:xmpp:ping"></ping>

**Comment by Caballlero** [comment]
![captura_20170226_001](https://cloud.githubusercontent.com/assets/24536606/23344097/8e153102-fc44-11e6-90f8-bd17873fa5d9.png)

**Comment by geobra** [comment]
Oh - this is a bug :-).

After reading the rfc again, it's clear that the ask attribute MUST only be used on server to server communication. Not on client to server communication. A Prosody jabber server seems to just ignore this wrong attribute. Whereas your jabber server is not so tolerant. Nevertheless I fix this bug with the next release.

Thank you for reporting this back to me!
