### ISSUE TITLE
// Any news harbour-shmoose  ??

### ISSUE THREAD

**Issue by Caballlero** [geobra/harbour-shmoose#11]
- Also i need help to compile from source. i have dificult in:
 Patch SConstruct file to do a PIC build of the library archive

Add:

* env.Append(CCFLAGS='-fPIC')

under the line 'env.SConscript = SConscript' on line 14

**Comment by geobra** [comment]
Development is slowed down currently because of lots of work at my real job. But I will speed up again in few month.

You are right, the documentation is not very good at the point, which file to patch. Use this one:
BuildTools/SCons/SConstruct

**Comment by Caballlero** [comment]
I get this 
 CXX Swiften/Session/SessionStream.o
  CXX Swiften/Session/BasicSessionStream.o
  CXX Swiften/Session/BOSHSessionStream.o
armv7hl-meego-linux-gnueabi-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugs.merproject.org/> for instructions.
scons: *** [Swiften/Session/BOSHSessionStream.o] Error 4
scons: building terminated because of errors.

**Comment by geobra** [comment]
That's an error from the MER virtual machine.
Increase memory (RAM) of the VM to 4 GB and try again.

**Comment by Caballlero** [comment]
thanks you very much.. i will try.

**Comment by Caballlero** [comment]
Now i get this error, i moved to 4GB  memory base VM.

Warning: Qt installation is missing packages. The following are required: Qt5Core Qt5WebKit Qt5Gui Qt5Widgets Qt5WebKitWidgets Qt5Multimedia Qt5X11Extras Qt5DBus Qt5Network

  Build Configuration
  -------------------
  Projects: Limber Swiften Sluift

  XML Parsers: Expat
  TLS Support: OpenSSL
  DNSSD Support: Disabled

scons: done reading SConscript files.
scons: Building targets ...
  CC 3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.o
3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.c:77:8: error: redefinition of 'struct ip_mreqn'
 struct ip_mreqn
        ^
In file included from /usr/include/netinet/in.h:37:0,
                 from 3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.c:55:
/usr/include/bits/in.h:119:8: note: originally defined here
 struct ip_mreqn
        ^
scons: *** [3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.o] Error 1
scons: building terminated because of errors.

**Comment by geobra** [comment]
That error I only got one time. On following new builds with fresh source trees, I never run into this problem again.

Comment out the complete struct ip_mreqn in
3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.c:77

**Comment by Caballlero** [comment]
i get this error with fresh source trees , also i did this  > 3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.c:77 #struct ip_mreqn

CC 3rdParty/LibIDN/src/gl/c-strcasecmp.o
  CC 3rdParty/LibIDN/src/gl/c-strncasecmp.o
  CC 3rdParty/LibIDN/src/gl/unistr/u8-check.o
  CC 3rdParty/LibMiniUPnPc/src/miniupnpc/igd_desc_parse.o
  CC 3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.o
3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.c:77:2: error: invalid preprocessing directive #struct
 #struct ip_mreqn
  ^
3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.c:78:1: error: expected identifier or '(' before '{' token
 {
 ^
scons: *** [3rdParty/LibMiniUPnPc/src/miniupnpc/miniupnpc.o] Error 1
scons: building terminated because of errors.

**Comment by Caballlero** [comment]
All the help much appreciated = )

**Comment by geobra** [comment]
Make sure your comment code looks like this:

```
//struct ip_mreqn
//{
//    struct in_addr  imr_multiaddr;      /* IP multicast address of group */
//    struct in_addr  imr_address;        /* local IP address of interface */
//    int     imr_ifindex;        /* Interface index */
//};

```

**Comment by Caballlero** [comment]
ok i get SUCCESS  build  on scons =  )
but what is the next ? 
[mersdk@SailfishSDK harbour-shmoose]$ mb2 -t SailfishOS-armv7hl build

Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.t5RrPI
+ umask 022
+ cd /home/mersdk/share/harbour-shmoose
+ LANG=C
+ export LANG
+ unset DISPLAY
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi -I/usr/lib/gfortran/modules'
+ export FFLAGS
+ LD_AS_NEEDED=1
+ export LD_AS_NEEDED
+ qmake CONFIG+=sailfishapp DEFINES+=SFOS
+ make -j2
g++ -c -pipe -DSWIFTEN_STATIC -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DSWIFT_EXPERIMENTAL_FT -std=c++11 -Wno-deprecated-declarations -Wno-placement-new -O2 -std=gnu++0x -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DSFOS -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../swift-3.0-arm/3rdParty/Boost/src -I../swift-3.0-arm/ -Isource -Isource/persistence -Isource/xep/httpFileUpload -Isource/xep/xmppPing -isystem /usr/include/sailfishapp -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++ -o main.o source/main.cpp
g++ -c -pipe -DSWIFTEN_STATIC -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DSWIFT_EXPERIMENTAL_FT -std=c++11 -Wno-deprecated-declarations -Wno-placement-new -O2 -std=gnu++0x -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DSFOS -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../swift-3.0-arm/3rdParty/Boost/src -I../swift-3.0-arm/ -Isource -Isource/persistence -Isource/xep/httpFileUpload -Isource/xep/xmppPing -isystem /usr/include/sailfishapp -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++ -o Shmoose.o source/Shmoose.cpp
In file included from source/Shmoose.cpp:1:0:
source/Shmoose.h:7:29: fatal error: Swiften/Swiften.h: No such file or directory
 #include <Swiften/Swiften.h>
                             ^
compilation terminated.
make: *** [Shmoose.o] Error 1
make: *** Waiting for unfinished jobs....
source/main.cpp:11:46: fatal error: Swiften/EventLoop/Qt/QtEventLoop.h: No such file or directory
 #include "Swiften/EventLoop/Qt/QtEventLoop.h"
                                              ^
compilation terminated.
make: *** [main.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.t5RrPI (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.t5RrPI (%build)
[mersdk@SailfishSDK harbour-shmoose]$

**Comment by Caballlero** [comment]
- Also i moved Swiften folder to harbour-shmoose then i get this error

[mersdk@SailfishSDK harbour-shmoose]$ mb2 -t SailfishOS-armv7hl build Swiften

Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.RRkoHg
+ umask 022
+ cd /home/mersdk/share/harbour-shmoose
+ LANG=C
+ export LANG
+ unset DISPLAY
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=neon -mthumb -Wno-psabi -I/usr/lib/gfortran/modules'
+ export FFLAGS
+ LD_AS_NEEDED=1
+ export LD_AS_NEEDED
+ qmake CONFIG+=sailfishapp DEFINES+=SFOS
+ make -j2
g++ -c -pipe -DSWIFTEN_STATIC -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DSWIFT_EXPERIMENTAL_FT -std=c++11 -Wno-deprecated-declarations -Wno-placement-new -O2 -std=gnu++0x -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DSFOS -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../swift-3.0-arm/3rdParty/Boost/src -I../swift-3.0-arm/ -Isource -Isource/persistence -Isource/xep/httpFileUpload -Isource/xep/xmppPing -isystem /usr/include/sailfishapp -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++ -o main.o source/main.cpp
g++ -c -pipe -DSWIFTEN_STATIC -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DSWIFT_EXPERIMENTAL_FT -std=c++11 -Wno-deprecated-declarations -Wno-placement-new -O2 -std=gnu++0x -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DSFOS -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../swift-3.0-arm/3rdParty/Boost/src -I../swift-3.0-arm/ -Isource -Isource/persistence -Isource/xep/httpFileUpload -Isource/xep/xmppPing -isystem /usr/include/sailfishapp -isystem /usr/include/mdeclarativecache5 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtCore -I. -I/usr/share/qt5/mkspecs/linux-g++ -o Shmoose.o source/Shmoose.cpp
In file included from ./Swiften/Base/API.h:9:0,
                 from ./Swiften/MUC/MUCManager.h:9,
                 from ./Swiften/Swiften.h:3,
                 from source/Shmoose.h:7,
                 from source/Shmoose.cpp:1:
./Swiften/Base/Platform.h:46:35: fatal error: boost/detail/endian.hpp: No such file or directory
 #include <boost/detail/endian.hpp>
                                   ^
compilation terminated.
make: *** [Shmoose.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from source/main.cpp:11:0:
./Swiften/EventLoop/Qt/QtEventLoop.h:9:28: fatal error: boost/thread.hpp: No such file or directory
 #include <boost/thread.hpp>
                            ^
compilation terminated.
make: *** [main.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.RRkoHg (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.RRkoHg (%build)
[mersdk@SailfishSDK harbour-shmoose]$

**Comment by geobra** [comment]
Move the swift folder back to its original location.
Then make sure the path to swift in the shmosse.pro file reflacts your setup. I did a host x86 and arm build of the swift library. The path in the original pro file may be different then in you locale configuration.

**Comment by Caballlero** [comment]
ok but how look like? it is better.

**Comment by Caballlero** [comment]
- Do not configure anything in shmosse.pro just move the whole folder to harbor-shmoose and it seemed that everything was fine until another problem appeared

 -lQt5Sql -lQt5Xml -lQt5Concurrent -lQt5Core -lGLESv2 -lpthread 
/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: ../swift-3.0-arm/Swiften/libSwiften.a(CoreClient.o): relocation R_ARM_THM_MOVW_ABS_NC against `_ZN5Swift10CoreClient21handleMessageReceivedEN5boost10shared_ptrINS_7MessageEEE' can not be used when making a shared object; recompile with -fPIC
../swift-3.0-arm/Swiften/libSwiften.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [shmoose] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.DHjmdT (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.DHjmdT (%build)
[mersdk@SailfishSDK harbour-shmoose]$

**Comment by geobra** [comment]
You are almost done :-).
It's just the last step, the linking of the binary, which fails. After that, the rpm packages gets build.

As the error message says, the swift library has to be build with 'Position Independent Code' (-fPIC). Because of this, one has to patch the swift library in the first step (modify the SConstruct file).

What could be wrong on your side:
- You patched the wrong file
- You patched it with wrong options
- You completely forgot to patch it

As you now have all items of the puzzle in place, I suggest you do a rm -rf on your build directory and restart from scratch with a clean setup.

**Comment by Caballlero** [comment]
geobra: Can you teach me how build with Position Independent Code ? i am learnig programing , i am green yet of this : /

**Comment by geobra** [comment]
Of course.
Look at your first questions and my answer on it in this thread.

**Comment by Caballlero** [comment]
ok

**Comment by Caballlero** [comment]
z -lssl -lcrypto -lxml2 -lresolv -ldl -lm -lc -lstdc++ -liphb -pie -rdynamic -lsailfishapp -lmdeclarativecache5 -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Sql -lQt5Xml -lQt5Concurrent -lQt5Core -lGLESv2 -lpthread 
/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
make: *** [shmoose] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.QKCFCh (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.QKCFCh (%build)

**Comment by Caballlero** [comment]
- I fixed that  with sb2 -t SailfishOS-armv7hl -m sdk-install -R zypper in libxml2-devel

**Comment by Caballlero** [comment]
ence.o moc_HttpFileuploader.o moc_HttpFileUploadManager.o moc_DownloadManager.o moc_FileModel.o moc_System.o moc_IpHeartBeatWatcher.o moc_MucManager.o   -Lswift-3.0-arm/Swiften -Lswift-3.0-arm/3rdParty/Boost -lSwiften -lSwiften_Boost -lrt -lz -lssl -lcrypto -lxml2 -lresolv -ldl -lm -lc -lstdc++ -liphb -pie -rdynamic -lsailfishapp -lmdeclarativecache5 -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Sql -lQt5Xml -lQt5Concurrent -lQt5Core -lGLESv2 -lpthread 
/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: swift-3.0-arm/Swiften/libSwiften.a(ExpatParser.o): undefined reference to symbol 'XML_SetUserData'
/srv/mer/targets/SailfishOS-armv7hl/usr/lib/libexpat.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [shmoose] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.74fLNZ (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.74fLNZ (%build)
[mersdk@SailfishSDK harbour-shmoose]$

**Comment by Caballlero** [comment]
[mersdk@SailfishSDK ~]$ sb2 -t SailfishOS-armv7hl -m sdk-install -R zypper in expat-devel
Loading repository data...
Reading installed packages...
'expat-devel' is already installed.
No update candidate for 'expat-devel-2.1.0-1.1.4.armv7hl'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.
[mersdk@SailfishSDK ~]$

**Comment by Caballlero** [comment]
> I need help to resolve:  DSO Dynamic Shared Object

**Comment by Caballlero** [comment]
- I fixed too the: DSO missing from command line error.  The  error was because i build    when a dependency was missing  
- Fixed after install libxml2-devel with new build swift-3.0.
- FINALLY i get build harbour-shmoose
Processing files: harbour-shmoose-0.2.5-1.armv7hl
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: libGLESv2.so.2 libQt5Concurrent.so.5 libQt5Core.so.5 libQt5Core.so.5(Qt_5) libQt5Gui.so.5 libQt5Gui.so.5(Qt_5) libQt5Network.so.5 libQt5Network.so.5(Qt_5) libQt5Qml.so.5 libQt5Qml.so.5(Qt_5) libQt5Quick.so.5 libQt5Quick.so.5(Qt_5) libQt5Sql.so.5 libQt5Sql.so.5(Qt_5) libQt5Xml.so.5 libQt5Xml.so.5(Qt_5) libc.so.6 libc.so.6(GLIBC_2.4) libc.so.6(GLIBC_2.7) libc.so.6(GLIBC_2.8) libc.so.6(GLIBC_2.9) libcrypto.so.10 libcrypto.so.10(libcrypto.so.10) libdl.so.2 libgcc_s.so.1 libgcc_s.so.1(GCC_3.5) libgcc_s.so.1(GCC_4.0.0) libiphb.so.0 libm.so.6 libm.so.6(GLIBC_2.4) libmdeclarativecache5.so.0 libpthread.so.0 libpthread.so.0(GLIBC_2.4) libresolv.so.2 libresolv.so.2(GLIBC_2.4) libresolv.so.2(GLIBC_2.9) librt.so.1 librt.so.1(GLIBC_2.4) libsailfishapp.so.1 libssl.so.10 libssl.so.10(libssl.so.10) libstdc++.so.6 libstdc++.so.6(CXXABI_1.3) libstdc++.so.6(CXXABI_ARM_1.3.3) libstdc++.so.6(GLIBCXX_3.4) libstdc++.so.6(GLIBCXX_3.4.11) libstdc++.so.6(GLIBCXX_3.4.15) libstdc++.so.6(GLIBCXX_3.4.5) libstdc++.so.6(GLIBCXX_3.4.9) libxml2.so.2 libxml2.so.2(LIBXML2_2.4.30) libxml2.so.2(LIBXML2_2.6.0) libz.so.1 rtld(GNU_HASH)
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/deploy/installroot
Wrote: /home/mersdk/share/harbour-shmoose/RPMS/harbour-shmoose-0.2.5-1.armv7hl.rpm
[mersdk@SailfishSDK harbour-shmoose]$

**Comment by Caballlero** [comment]
# thank you so so much geobra for the full support.

**Comment by geobra** [comment]
Great that you finally had success on building shmoose.
Please be aware of the fact that the database format has changed due to some new features. So if you do an upgrade from a previous version, you won't see your 'old' messages any longer with this new version.

**Comment by Caballlero** [comment]
ok.
