### ISSUE TITLE
Shmoose stop working with SFOS 4.3.0 (libcrypto.so.10 problem)

### ISSUE THREAD

**Issue by sativista** [geobra/harbour-shmoose#113]
When I was upgrading to SFOS 4.3.0 I've to uninstall shmoose, and now I can't get it installed again.

It complains about libcrypto.so.10, which is deprecated now. 

There is some chance to correct this bug?

**Comment by geobra** [comment]
You can install that missing lib from openrepos. I am also working on a new version, which is build with the newest SFOS SDK. This will be released until end of this year.

**Comment by sativista** [comment]
Ok, thank you very much geobra!

https://openrepos.net/content/lpra7/openssl-102-legacy-jollaphone-x-xa2
is this the right one?

**Comment by geobra** [comment]
Don't know for sure. But there is a discussion on OpenRepos about that issue. Please have a look there.

**Comment by geobra** [comment]
Please try 0.8.0 on openrepos.
