### ISSUE TITLE
Missed to update web-pages

### ISSUE THREAD

**Issue by Olf0** [geobra/harbour-shmoose#122]
This is a reminder to update the web-page at https://geobra.github.io/harbour-shmoose/ with the recent content at https://github.com/geobra/harbour-shmoose/tree/master/doc/architecture

Specifically these three sections have newer content in the git-SCM than in the WWW:
* https://github.com/geobra/harbour-shmoose/blob/master/doc/architecture/src/02_architecture_constraints.adoc -> (outdated) https://geobra.github.io/harbour-shmoose/#section-architecture-constraints
* https://github.com/geobra/harbour-shmoose/blob/master/doc/architecture/src/11_technical_risks.adoc -> (outdated) https://geobra.github.io/harbour-shmoose/#section-technical-risks
* https://github.com/geobra/harbour-shmoose/blob/master/doc/architecture/src/12_glossary.adoc -> (outdated) https://geobra.github.io/harbour-shmoose/#section-glossary

Please update the web-page content rsp. sections with the current content in the SCM.
Thanks!

**Comment by geobra** [comment]
That should update automatically. I will check it...

**Comment by geobra** [comment]
Please have a look at the pages. They should be updated now :-).

**Comment by Olf0** [comment]
> That should update automatically. I will check it...

… the automatic update?
I.e., is that fixed now, or did you manually update?

In case of a manual update, I suggest to reopen this issue until the automatic update is either fixed or specified as non-functional (i.e., defined as "won't fix").

**Comment by geobra** [comment]
This was a manual update of the documentation. I did not get it running again to update the doc automatically. The previous way of doing it does not work any more and currently I have no time to have a deeper look.
With this, for now, 'Won't fix' ;-).

**Comment by Olf0** [comment]
That is O.K. for me; I was just curious to know the and had the idea that this rather should be denoted.
