### ISSUE TITLE
No packet mce-tools available

### ISSUE THREAD

**Issue by DLFW** [geobra/harbour-shmoose#123]
Hi, maybe this is a noob-problem, but when I try to install the mce tools (`pkcon install mce-tools`), pkcon tells me that this package does not exists. Discription outdated?

I'm using Sailfish 4.3.0.12.

Would greatly appreciate an update of the readme or any help. :smile:

**Comment by geobra** [comment]
Be aware of the fact that you have to do this with the root user. Or by adding
 devel-su before each command.

**Comment by DLFW** [comment]
Thanks. Well, yesterday I openend a shell with `devel-su bash` and invoked the command from within there. Also, `pkcon` clearly complained about the package not being found and not a permission issue.

However, I just tried it again and now it works. `pkcon` found the package. Strange. Closing this. Thanks for the reply anyway. ;)
