### ISSUE TITLE
image uploads seems to be missing ui?

### ISSUE THREAD

**Issue by poetaster** [geobra/harbour-shmoose#126]
I'm on a Vollaphone, SFOS 4.4. Everything seems to work, except for a means to upload an image?
I had set the paths to include ones which where useable (/home/defaultuser/Pictures/Camera, for instance).

**Comment by geobra** [comment]
There should be a paperclip icon right beside the message input field. This will change to a send-button, as soon as you start typing. If you touch on the paperclip icon, the image-picker or file-picker dialog should show up. 
Can you post screen-shot of the message page?

**Comment by poetaster** [comment]
Ok, there is no paperclip icon, just the text entry field and, to the right, the send icon. I could look at the source....

**Comment by geobra** [comment]
Have a look here:
https://github.com/geobra/harbour-shmoose/blob/e204f777698cbb3cd8e77b49e10bdc8c4691a9fd/resources/qml/pages/MessagingPage.qml#L507

To have the paperclip icon, it is basically:
- No text message typed in
- No attachment to send already selected
- The logged-in xmpp server announced support for http upload

**Comment by geobra** [comment]
You can also start shmoose via command line and watch for this line:
https://github.com/geobra/harbour-shmoose/blob/e204f777698cbb3cd8e77b49e10bdc8c4691a9fd/source/base/DiscoInfoHandler.cpp#L48

... to make sure, the connected server is capable to support http upload.

**Comment by poetaster** [comment]
> You can also start shmoose via command line and watch for this line:
> 
> https://github.com/geobra/harbour-shmoose/blob/e204f777698cbb3cd8e77b49e10bdc8c4691a9fd/source/base/DiscoInfoHandler.cpp#L48
> 
> ... to make sure, the connected server is capable to support http upload.
The disco stanza seems?:
``` 
<iq xmlns="jabber:client" from="netzpolitik.org" type="result" id="1d1bdb31-7e38-4dc1-8908-a6f76402b77c" to="test@netzpolitik.org/shmoose">
  <query xmlns="http://jabber.org/protocol/disco#info">
   <identity name="HTTP File Upload" type="file" category="store"></identity>
   <identity name="Prosody" type="im" category="server"></identity>
   <identity name="SOCKS5 Bytestreams Service" type="bytestreams" category="proxy"></identity>
   <feature var="urn:xmpp:carbons:rules:0"></feature>
   <feature var="urn:xmpp:carbons:2"></feature>
   <feature var="urn:xmpp:http:upload:0"></feature>
   <feature var="urn:xmpp:blocking"></feature>
   <feature var="urn:xmpp:ping"></feature>
   <feature var="jabber:iq:roster"></feature>
   <feature var="jabber:iq:last"></feature>
   <feature var="http://jabber.org/protocol/disco#info"></feature>
   <feature var="http://jabber.org/protocol/disco#items"></feature>
   <feature var="http://jabber.org/protocol/commands"></feature>
   <feature var="urn:xmpp:time"></feature>
   <feature var="jabber:iq:time"></feature>
   <feature var="vcard-temp"></feature>
   <feature var="jabber:iq:private"></feature>
   <feature var="http://jabber.org/protocol/bytestreams"></feature>
   <feature var="msgoffline"></feature>
   <feature var="jabber:iq:version"></feature>
   <feature var="jabber:iq:register"></feature>
   <x xmlns="jabber:x:data" type="result">
    <field var="FORM_TYPE" type="hidden">
     <value>urn:xmpp:http:upload:0</value>
    </field>
    <field var="max-file-size" type="text-single">
     <value>10485760</value>
    </field>
   </x>
  </query>
 </iq>
```
Hmmm. most clients seem happy with http_file_share active (prosody 0.12). file shaing works with pidgin, psi, jsxc, dino....?

**Comment by poetaster** [comment]
Possibly the domain? In dns I point upload.xmpp.netzpolitik.org CNAME xmpp.netzpolitik.org. There are SRV records for netzpolitik.org. There are disco items for domains netzpolitik.org and xmpp. Hmmm.

**Comment by poetaster** [comment]
Oh, boy. In trying to make sure it's discoverable, I think I broke uploads. hmmm. That xmpp server is now 'in flux'.

**Comment by poetaster** [comment]
Ok, fixed it for some measure of fixed. I manage to send files from, for instance, dino (0.3) to shmoose. shmoose get's the data (omemo works! yeah!) but does not display it inline. click and it shows. So, for some measure of file sharing it works.

**Comment by poetaster** [comment]
Ok, I managed it with adding http_upload to the Virtuals. Confusing http_file_share and http_upload. It's a bit odd, since some clients 'deal' fine with 'only file sharing'. In any case, shmoose works !

**Comment by geobra** [comment]
Thank you for the feedback. Glad to hear that it is now also working on your side.
