### ISSUE TITLE
If Gajim and Shmoose are open at the same time, the messages are not delivered to Shmoose

### ISSUE THREAD

**Issue by marmistrz** [geobra/harbour-shmoose#34]

**Comment by d9h20f** [comment]
Does your server support Message Carbons?

**Comment by marmistrz** [comment]
Yes, my server is wiuwiu.de, it supports the XEP: https://conversations.im/compliance/
The same scenario worked on Conversations + Gajim.

Tested with messages incoming from a friend who uses an IRC bridge and the same happens, so removed Conversations from the title.

**Comment by marmistrz** [comment]
Further notes: messages sent by me (Gajim) are not shown in Shmoose, but vice-versa it works.
The same issue can be reproduced with Swift IM 3.0. The issue is gone when using swift-im 4.0rc5.
