### ISSUE TITLE
Joining forces in building multichat app based on libpurple.

### ISSUE THREAD

**Issue by muppeth** [geobra/harbour-shmoose#42]
I hope I don't offend anyone as I appreciate all the efforts, but wouldnt it be better to combine the work of few people that started working on various xmpp clients and help out with https://github.com/Michal-Szczepaniak/Morsender
Since its based on libpurple, most of the work (including omemo) is done by libpurple already. Plus the app has potential to support multiple (almost all) existing protocols which would be one of a kind app in the mobile world. As far as I see the main dev is not much interested in xmpp, so I thought maybe you guys would want to jump onboard and put the missing pieces for xmpp. 

It's just a suggestion from yet another person that has no clue about qml, so if you don't think this is a good idea, feel free to ignore it.

**Comment by geobra** [comment]
For me, as a C++ developer, I would like to use librarys written in modern languages. libpurple is feature rich but still in plain C. Swiften is written in modern C++ 11 and 14. Also Morsender seems to be in a very  early stage. Let's see how it will go forward.
