### ISSUE TITLE
ability to delete conversations

### ISSUE THREAD

**Issue by ghost** [geobra/harbour-shmoose#47]
needs to be implemented to deal with spam.

**Comment by geobra** [comment]
It is not difficult to implement this. If someone new wants to jump in here and start to support this project, I will mentor this.

**Comment by ron282** [comment]
Hi geobra.I'd like to implement it. If you can help me that would be great.

**Comment by geobra** [comment]
Sure. 

Start in 'resources/qml/pages/MessagingPage.qml':191 by adding a new MenuItem 'delete'. To be complient with the Sailfish UI, there should be the countdown where one can cancel the delete within 5 seconds. I have never done this. So this is a research task for you ;-). The delete function should be assigned with an 'onClicked' handler which calls the actual delete method in the class 'shmoose.persistence.deleteMessage(conversationId, id)'

source/persistence/Persistence.h:
add a Q_INVOKABLE void deleteMessage(const QString& jid, const QString& msgId)
This is acutally just a proxy to messageController. Have a look at the other methods, it should be clear.

Class source/persistence/MessageController
Add a method which does the job. Construct a sql statement which deletes the msg. Use the jid and msgId as a filter to exact match the message in the database. This database is bound to the qml UI. As soon as the sql statement executes, the UI will automatically be updated. Have a look at isMessageIdForJidInDatabase which do a search on exact that parameters. A similar statement can be used with a delete.

Thats all. If something fails or is unclear, feel free to ask.

**Comment by ron282** [comment]
Thanks 

This is almost finished. I need to fix a bug regarding deleting attachments and I send a pull request.

**Comment by geobra** [comment]
Maybe one more thing. I am not sure about MaM (Message Archive Management). Could happen that if the message gets removed from the local database, it will be refetched from the server. If this really happens, we must have a look at the MaM xep about also deleting this message from the server...

**Comment by geobra** [comment]
Implemented by @ron282. Merged with #95.
