### ISSUE TITLE
Ubuntu Touch port?

### ISSUE THREAD

**Issue by poVoq** [geobra/harbour-shmoose#55]
Would be cool if this would be also available on Ubuntu Touch. Seems the two systems ar reasonably compatible for this to work in theory.

Thanks for looking into it.

**Comment by geobra** [comment]
Hi

Ubuntu Touch also uses Qt with Qml. So what is needed is basically a cross compilation to that new target and a new UI using qml. Sailfish uses Qml Silica, which is not available at UT. 

The hardest part would be the integration into the UT system. On Sailfish, the apps are allowed to run in parallel. This makes it really easy to handle 'long-term TCP connections' as needed for xmpp. As far as I know, only one app is allowed to run at one time on UT. Also I don't know if it is possible to implement something like a daemon on UT.

My main target is Sailfish. So it needs someone to look into this things for the Ubuntu Touch target. I can't afford this additionally - sorry.

**Comment by geobra** [comment]
One additional comment:
As far as I know, Kaidan [1] has an Ubuntu Touch target.

[1] https://github.com/KaidanIM/Kaidan

**Comment by cibersheep** [comment]
Hello. Sorry for the «spam» as it's clear it's out of the scope of your app but I think it might be useful for someone reading this thread: as you mention, UT doesn't let apps running in the background (but can be hacked with UT Tweak Tool).
More interesting is that is possible to run deamons, the port of Linphone [uses one](https://gitlab.com/ubports-linphone/linphone-simple/blob/master/linphone/bin/linphone-daemon).

Anyhow, thanks and sorry for the offtopic :)

**Comment by mdehollander** [comment]
I am using UT on my phone as well and had this project bookmarked as potential porting app. Since shmoose is a fork of Kaidan and both are maintained, my question would be what are the main differences (features, layout). I would love to see a native xmpp client on UT.

Would it be an idea to take a look at how teleports and fluffychat handle jobs running in the background? They both support notifications, so there should be something running isn't it?

**Comment by geobra** [comment]
Shmoose and Kaidan get forked during the first lines of code. I doubt that this two projects have currently something in common from a source code point of view. I don't know the current supported features of Kaidan. This comperison has to be done by yourself ;-). 

In my opinion both projects can be cross compiled to the UT target. What you need to do for both projects is the new qml ui. You can start with a really simple UI. You don't have to integrate all the feature from the backend which are possible as a starting point. So I would encourage you to start with this. If this is done you can have a look on how to keep the app up and running and what is needed to be done for the notification integration.
