### ISSUE TITLE
featureRequest: Manage notifications

### ISSUE THREAD

**Issue by juanro49** [geobra/harbour-shmoose#61]
Hello, could you integrate in the future the possibility to mute chat notifications? I think it's a good option (especially for groups)

Thanks!!

**Comment by geobra** [comment]
I also thought about that for the exact same use-case. It is not hard to implement. Do you want to try? I can give you some advice if needed.

**Comment by juanro49** [comment]
I'll be glad to test (unfortunately, I don't have any knowledge of QML, C++ and the inner workings of Sailfish apps yet)

**Comment by mazhe** [comment]
Hey, if you're still interested, PR https://github.com/geobra/harbour-shmoose/pull/74 (now included in shmoose) should handle this quite gracefully now : 
- Notifications can be enabled/disabled globally for chat and/or groupchat from the settings page
- Specific conversations can override the global choice (by swiping right in the conversation)
