### ISSUE TITLE
Translations: add French to weblate

### ISSUE THREAD

**Issue by Mejans** [geobra/harbour-shmoose#66]
Almost everything is in the title ^^
Thanks!

**Comment by Tititesouris** [comment]
Hello @Mejans, native French here, I'm on it! :)

**Comment by Tititesouris** [comment]
Ahh, nevermind. I thought I could just fork and PR, I'm not familiar with Weblate.

**Comment by geobra** [comment]
Decision of you both. 
I can add French to weblate. But if you prefer, just fork and PR. I will accept this also :-).

**Comment by Tititesouris** [comment]
Ok, great, then I will work on a PR ASAP :)

**Comment by Mejans** [comment]
Merci petitesouris :)

**Comment by Tititesouris** [comment]
I have a few questions:
- Most "source" tags are capitalized, but some are lowercased, is that on purpose?
- Some of the lowercase "source" tags have capitalized English "translation" tags, is that on purpose? Shouldn't the translation match the capitalization of the source?
- What is JID?
- "About" as in "About page" is hard to translate, what is the context exactly? (<location filename="../qml/pages/MenuPage.qml" line="63"/>) It might be needed to translate it to something like "More information", "Description", "What is X?", etc...
- What is a "search path" for an attachment?
- In <location filename="../qml/pages/PreferencesPage.qml" line="33"/>, is there 1 attachment with multiple search paths, or multiple attachments with multiple search paths, or multiple attachments with a single search path each?

Thank you :)

**Comment by Mejans** [comment]
JIB : Jabber ID, leave it like it.
Put «À propos» for about, it may be a like to the About page.

**Comment by geobra** [comment]
Hi
- Source tags:
You are right, some of the source tags have a wrong caption. That has to be fixed in the code as well as in the ts files.
- About
 About is used to display a page about Shmoose itself. The version, the github url and the contributors
- Search path
  Yes, that is a configurable path where the available attachments are searched
  There can be multiple search paths, but can only select one attachment

You are welcome :-).

**Comment by Tititesouris** [comment]
Here's the PR #67 
If you edit the tags in the code (or let me know which tags need capitalization and which file to change), then the translation capitalization should be reviewed too, probably for every language. Let me know if you'd like me to do that too.

**Comment by Tititesouris** [comment]
Also, could someone add the "hacktoberfest" topic to this repository, so I can count this PR towards my Hacktoberfest goal? :)
