### ISSUE TITLE
GPG encryption planned?

### ISSUE THREAD

**Issue by mase76** [geobra/harbour-shmoose#8]
Hi!
Is there a plan to support GPG encryption?

**Comment by geobra** [comment]
Currently its planned to implement omemo, as soon as MUC is done. Sorry, no GPG.

**Comment by tchncs** [comment]
I think omemo is more important anyway... .

**Comment by mase76** [comment]
OMEMO is the more comfortable technique, but worse when having multiple
devices. With forward secrecy things like message-archive-managment or
message-carbons don't work. I hope, that will change in the future.
Therefor I still use GPG.
"Conversations" on Android is still the XMPP client with the best
functionality. It implements OpenPGP, OMEMO and even still OTR.
And it implements all the XEPs you need today. Losing one of those
would make it falling behind the big players.
It is the best example for a XMPP messenger. Maybe you should contact
its developer to get further help. He is very engaged with the XMPP
protocol. I am sure, he would help.
I hope, Shmoose will become the equivalent on Sailfish OS. There are
no more candidates at this time.
I can only help testing, as I run my own XMPP server.

**Comment by geobra** [comment]
You are totally right with your description about Omemo and GPG. Maybe in the future, after Version 1.0 is ready I will think about implementing more encryption standards. And I am of course already in contact with Daniel, who is the author of Conversations. He gave me some important hints at project start.

**Comment by mase76** [comment]
I hope you will get it to a great messenger with all the encryption. This is needed on Sailfish OS urgent, as there is nothing similar so far.

**Comment by d9h02f** [comment]
> With forward secrecy things like message-archive-managment or message-carbons don't work.

They do, just not when you add a new device (which usually doesn't happen very often). Conversations is also planning to be OMEMO-exclusive once a critical mass is reached of servers supporting it, so I think working on GPG or OTR support would be a wasted effort.

**Comment by geobra** [comment]
We will concentrate on OMEMO for now.
