### ISSUE TITLE
Visual artifact -- MUC topic "spilled" over roster and conversation list

### ISSUE THREAD

**Issue by briest** [geobra/harbour-shmoose#85]
Testing Shmoose (openrepos version) on Xperia X, SFOS 3.4.0.24, I've noticed strange visual artifact: roster (Contacts) and Conversations are overlaid with "topic" (actually, quite long wall of text, over 1kB) from one of MUCs. Namely, it's always blabber@conference.blabber.im, although I have several other MUCs open (but their topics are typical oneliners).
In addition, entry of blabber@conference.blabber.im in conversations list lacks all texts: room name, jid, last message, and when I enter the room, there are no messages (I have checked with Gajim and Conversations, that the MUC is alive and chatty ;) ). On the screenshot, it's the line where "Videokonferenz" is; "Videokonferenz" comes from MUC topic.
Seems Shmoose somehow chokes on the enormous "topic".

![shmoose](https://user-images.githubusercontent.com/77794220/105374231-c1bf5380-5c07-11eb-95b6-be5fa52b860c.png)

**Comment by geobra** [comment]
Sounds strange. Obviously, the long topic could be a reason for this. Will have a look at this. The missing chats inside the group could be a bug in old Shmoose versions. Which version are you using here?

**Comment by briest** [comment]
I use version from openrepos -- 0.7.0. I have a gut feeling, that lack of messages in chat has the same reason, probably related to the problems caused by topic, for it happens in the very same room and only there.

**Comment by geobra** [comment]
Give me some time. Will have a look at it.

**Comment by geobra** [comment]
Ok, can it reproduce. The multiline artifact is the result of a really long subject with line breaks. This is easy to fix by limiting this on the mobile UI. But there are also some serializer errors on the console from the room messages. Have to look deeper into that.

**Comment by geobra** [comment]
Good news: Problem solved by fixing the long subject with that breaks.
Bad news: Serializer errors are within the omemo branch. Must have a look at that now.

Resolved with version 0.7.1
