### ISSUE TITLE
run in daemon?

### ISSUE THREAD

**Issue by Caballlero** [geobra/harbour-shmoose#9]
HI
- There plans to run in the background, to receive notifications even if the app is not open?
- also can you add strings of words to translate?

**Comment by geobra** [comment]
As far as I can tell, Daemon Mode is just an automatic App startup without showing the gui on boot. So it makes no difference if you leave the app open in the background, or start in daemon mode. But it is of course more comfortable.

i18n will be started some time in the future when the UI gets more stable. Sometimes before Version 1.0 ;-).

**Comment by Caballlero** [comment]
- It would be nice if there was an option to activate daemon mode like whatsap do you think? Do you think it makes sense what I say with the protocologo xmpp?
- I really like a lot of SHMOOSE and I'm going to > VOTE < for it.
- Being able to send files is urgently needed.

**Comment by geobra** [comment]
Daemon mode is independent of the protocol. It's a decision if it makes sense for the app to be run all the time. This should be work for shmoose but isn't my highest priority at the moment

I did some testing with xep 0234 which describes direct file transfer between two users. The downside of this is that both users have to be online at the same time. This dosen't work really good for a mobile client. That is what http-upload is for. One client stores the file on a server and just sends the link to the other client. This is already implemented in shmoose. You can try this by using the paper clip in the message sending page. The UI isn't as good as it could be for now ;-).

Thank you for the vote :-).

**Comment by Caballlero** [comment]
please close this
